# Generated by Django 4.0.5 on 2022-07-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_alter_voter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('likes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('candidtate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voter.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CandidateComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('candidateCampaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voter.candidatecampaigns')),
            ],
        ),
    ]
