# Generated by Django 4.0.5 on 2022-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_candidatecampaigns_voter_is_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaigns',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
