# Generated by Django 4.0.4 on 2022-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_candidate_candidate_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatecampaigns',
            old_name='candidtate',
            new_name='candidate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_username',
            field=models.CharField(default='raju', max_length=255),
        ),
    ]
